@CarRental.Api_HostAddress = http://localhost:5201
@host = http://localhost:5201

GET {{host}}/weatherforecast/
Accept: application/json

###

Get {{host}}/api/cars/2
Accept: application/json

###
POST {{host}}/api/cars
Content-Type: application/json

{
    "brand": "Chevrolet",
    "model": "Corolla",
    "price": 120,
    "year": 2023,
    "color": "green"
}
        
###
GET {{host}}/api/cars/
Accept: application/json

###
PUT {{host}}/api/cars/2
Content-Type: application/json

{
    "id": 2,
    "brand": "Mazda",
    "model": "Civic",
    "price": 100,
    "year": 2022,
    "color": "black"
}

###
DELETE {{host}}/api/cars/3

###Alquiler de autos
POST {{host}}/api/rental
Content-Type: application/json

{
    "userId": 2,
    "carId": 1,
    "startDate": "2025-07-01T10:00:00",
    "endDate": "2025-07-05T10:00:00"
}

###
GET {{host}}/api/rental/1
Accept: application/json

###
DELETE {{host}}/api/rental/1



